import type { Metadata } from "next";
import "./globals.css";
import Dock from "./components/Dock";

export const metadata: Metadata = {
  title: "Jeongeun Lee",
  description: "Generated by outoro",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen bg-black text-white">
        {children}
        <Dock />
      </body>
    </html>
  );
}
