import type { Metadata } from "next";
import "../styles/globals.css";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import { ThemeProvider } from "../components/ThemeButton/ThemeProvider";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Jeongeun Lee",
  description: "Generated by outoro",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="ko">
      <body  className="font-Pretendard text-[#101010] dark:text-[#ededed]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
