export const projects = [
  {
    id: 1,
    name: "remonth(다시 한 달)",
    description: "New web design for the blockchain investment fund Maven 11.",
    year: "January, 2013",
    techStack: [
      "React",
      "Redux Toolkit",
      "Firestore Database",
      "Firebase Auth",
      "Sass",
      "Framer Motion",
      "Vercel",
    ],
    videoId: "7ihLv8_Vd-4",
    serviceLink: "https://remonth.vercel.app/",
    githubLink: "https://github.com/outoro/remonth",
    readmeLink: "https://github.com/outoro/remonth",
  },
  {
    id: 2,
    name: "2023 Portfolio",
    description: "New web design for the blockchain investment fund Maven 11.",
    year: "January, 2013",
    techStack: ["Tailwind CSS", "Vercel"],
    videoId: "7ihLv8_Vd-4",
    serviceLink: "https://www.naver.com/",
    githubLink: "https://github.com/outoro/portfolio",
    readmeLink: "https://github.com/outoro/remonth",
  },
];
